# Generated by Django 4.0.2 on 2022-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
